# Generated by Django 5.1.6 on 2025-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_time_login",
            field=models.BooleanField(default=True),
        ),
    ]
