# Generated by Django 5.1.6 on 2025-03-03 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_first_time_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
    ]
