# Generated by Django 5.1.6 on 2025-03-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_admin", "0005_rename_productcategory_inventorycategory_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="is_reusable",
            field=models.BooleanField(default=False),
        ),
    ]
