# Generated by Django 5.1.6 on 2025-03-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_admin", "0006_inventory_is_reusable"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
