# Generated by Django 5.1.6 on 2025-03-07 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_admin", "0007_inventory_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="price",
            new_name="unit_price",
        ),
    ]
