# Generated by Django 5.1.6 on 2025-03-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesteditems",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="nurse.request",
            ),
        ),
    ]
