# Generated by Django 5.1.6 on 2025-03-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0002_alter_requesteditems_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesteditems",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
