# Generated by Django 5.1.6 on 2025-03-07 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="unit_price",
        ),
    ]
