# Generated by Django 5.1.6 on 2025-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_cartitem_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_products",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
