# Generated by Django 5.1.6 on 2025-03-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_cart_total_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
