# Generated by Django 5.1.6 on 2025-03-10 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_cart_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="updated_by",
        ),
    ]
