# Generated by Django 5.1.6 on 2025-03-05 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nurse",
            old_name="organization_id",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="nurse",
            old_name="user_id",
            new_name="user",
        ),
    ]
