# Generated by Django 5.1.6 on 2025-03-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_manager",
            "0002_rename_organization_id_nurse_organization_and_more",
        ),
        ("main_admin", "0004_inventorymanager_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nurse",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main_admin.organization",
            ),
        ),
    ]
