# Generated by Django 5.1.6 on 2025-03-05 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_manager", "0004_supplier"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
