# Generated by Django 5.1.6 on 2025-03-06 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_manager", "0007_orginventory_delete_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orginventory",
            name="is_reusable",
        ),
    ]
