# Generated by Django 5.1.6 on 2025-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_manager", "0008_remove_orginventory_is_reusable"),
    ]

    operations = [
        migrations.AddField(
            model_name="orginventory",
            name="delivered_stock",
            field=models.IntegerField(default=0),
        ),
    ]
