# Generated by Django 5.1.6 on 2025-03-12 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_manager", "0009_orginventory_delivered_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orginventory",
            name="delivered_stock",
        ),
    ]
